/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.HeadlessException;
import javax.swing.JOptionPane;
import model.EquipeDAO;
import model.TorneioDAO;
import model.TorneioHasEquipeDAO;

/**
 *
 * @author gustavo
 */
public class EditarEquipe extends javax.swing.JFrame {

    /**
     * Creates new form EditarEquipe
     */
    public EditarEquipe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_editarDados = new javax.swing.JButton();
        btn_cadastrarMembros = new javax.swing.JButton();
        lbl_nomeEquipe = new javax.swing.JLabel();
        btn_torneioHasEquipe = new javax.swing.JButton();
        btn_apagarEquipe = new javax.swing.JButton();
        btn_cancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(234, 91, 12));

        btn_editarDados.setText("Editar Nome");
        btn_editarDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editarDadosActionPerformed(evt);
            }
        });

        btn_cadastrarMembros.setText("Cadastrar Membros");
        btn_cadastrarMembros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadastrarMembrosActionPerformed(evt);
            }
        });

        lbl_nomeEquipe.setText("Equipe: " + TelaInicial.getSelectedValueNomeEquipe());

        btn_torneioHasEquipe.setText("Adicionar a um Torneio");
        btn_torneioHasEquipe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_torneioHasEquipeActionPerformed(evt);
            }
        });

        btn_apagarEquipe.setText("Apagar Equipe");
        btn_apagarEquipe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_apagarEquipeActionPerformed(evt);
            }
        });

        btn_cancelar.setText("Cancelar");
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(lbl_nomeEquipe))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(btn_editarDados))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(btn_torneioHasEquipe))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(btn_apagarEquipe))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(btn_cancelar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(btn_cadastrarMembros)))
                .addContainerGap(102, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lbl_nomeEquipe)
                .addGap(11, 11, 11)
                .addComponent(btn_editarDados)
                .addGap(18, 18, 18)
                .addComponent(btn_cadastrarMembros)
                .addGap(18, 18, 18)
                .addComponent(btn_torneioHasEquipe)
                .addGap(18, 18, 18)
                .addComponent(btn_apagarEquipe)
                .addGap(18, 18, 18)
                .addComponent(btn_cancelar)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cadastrarMembrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadastrarMembrosActionPerformed
        // TODO add your handling code here:

        CadastroMembros cadastroMembros = new CadastroMembros();
        cadastroMembros.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        cadastroMembros.setVisible(true);
    }//GEN-LAST:event_btn_cadastrarMembrosActionPerformed

    private void btn_editarDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editarDadosActionPerformed
        // TODO add your handling code here:
        String novoNome = JOptionPane.showInputDialog(null,
                "Digite o novo nome", "Alteração",
                JOptionPane.INFORMATION_MESSAGE);
        EquipeDAO daoEquipe = new EquipeDAO();
        try {
            if (!novoNome.isEmpty()) {
                if (daoEquipe.atualizaNomeEquipe(TelaInicial.getSelectedValueNomeEquipe(), novoNome)) {
                    JOptionPane.showMessageDialog(null, "Nome atualizado!");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Impossível alterar o nome. O campo está vazio.");
            }
        } catch (NullPointerException ex) { // Este TryCatch está sendo usado para tratar um erro que ocorre ao apertar o botão cancelar

        }

    }//GEN-LAST:event_btn_editarDadosActionPerformed

    private void btn_torneioHasEquipeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_torneioHasEquipeActionPerformed
        // TODO add your handling code here:

        String selectedValueNomeTorneio;

        TorneioDAO daoTorneio = new TorneioDAO();
        TorneioHasEquipeDAO daoTorneioHasEquipe = new TorneioHasEquipeDAO();

        if (!daoTorneio.listaTorneios().isEmpty()) {
            Object[] itens = daoTorneio.listaTorneios().toArray();
            selectedValueNomeTorneio = (String) JOptionPane.showInputDialog(null,
                    "Selecione a Equipe", "Opçao", JOptionPane.INFORMATION_MESSAGE, null,
                    itens, itens[0]);

            if (selectedValueNomeTorneio != null) {
                if (daoTorneioHasEquipe.inserirEquipeTorneio(TelaInicial.getSelectedValueNomeEquipe(), selectedValueNomeTorneio)) {
                    JOptionPane.showMessageDialog(null, "Equipe " + TelaInicial.getSelectedValueNomeEquipe() + " inserida do torneio " + selectedValueNomeTorneio);
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Nenhum Torneio Cadastrado");
        }
    }//GEN-LAST:event_btn_torneioHasEquipeActionPerformed

    private void btn_apagarEquipeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_apagarEquipeActionPerformed
        // TODO add your handling code here:

        EquipeDAO daoEquipe = new EquipeDAO();

        if (daoEquipe.deletarEquipe(TelaInicial.getSelectedValueNomeEquipe())) {
            JOptionPane.showMessageDialog(null, "Equipe excluída");
            this.dispose();
        }

    }//GEN-LAST:event_btn_apagarEquipeActionPerformed

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btn_cancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditarEquipe.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditarEquipe.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditarEquipe.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditarEquipe.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditarEquipe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_apagarEquipe;
    private javax.swing.JButton btn_cadastrarMembros;
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_editarDados;
    private javax.swing.JButton btn_torneioHasEquipe;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_nomeEquipe;
    // End of variables declaration//GEN-END:variables
}
